# Generated by Django 4.0.5 on 2022-07-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demonios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creardemonio',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='creardemonio',
            name='reseña',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
