# Generated by Django 4.0.5 on 2022-07-25 03:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demonios', '0002_creardemonio_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creardemonio',
            name='reseña',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
