# Generated by Django 4.0.5 on 2022-07-25 03:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creardios',
            name='autor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='creardios',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='creardios',
            name='reseña',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
